apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - args:
        - mysqld
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --max_connections=200
        - --max_heap_table_size=128M
        - --max_allowed_packet=32M
        - --tmp_table_size=128M
        - --join_buffer_size=128M
        - --innodb_buffer_pool_size=1G
        - --innodb_doublewrite=ON
        - --innodb_flush_log_at_timeout=3
        - --innodb_read_io_threads=32
        - --innodb_write_io_threads=16
        - --innodb_buffer_pool_instances=9
        - --innodb_file_format=Barracuda
        - --innodb_large_prefix=1
        - --innodb_io_capacity=5000
        - --innodb_io_capacity_max=10000
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: TZ
          value: America/Los_Angeles
        image: mariadb:10.3
        imagePullPolicy: ""
        name: cacti-db
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: cacti-db
      hostname: db
      restartPolicy: Always
      serviceAccountName: ""
      subdomain: cacti-db-sub
      volumes:
      - name: cacti-db
        persistentVolumeClaim:
          claimName: cacti-db
status: {}
