apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-1598632812
  labels:
    app: chart-1598632812
spec:
  selector:
    matchLabels:
      app: chart-1598632812
  template:
    metadata:
      labels:
        app: chart-1598632812
    spec:
      containers:
      - name: cacti
        image: smcline06/cacti
        imagePullPolicy: IfNotPresent
        env:
         - name: "DB_NAME"
           value: "cacti_master"
         - name: "DB_USER"
           value: "cactiuser"
         - name: "DB_PASS"
           value: "cactipassword"
         - name: "DB_HOST"
           value: "db"
         - name: "DB_PORT"
           value: "3306"
         - name: "DB_ROOT_PASS"
           value: "rootpassword"
         - name: "INITIALIZE_DB"
           value: "1"
         - name: "TZ"
           value: "America/Los_Angeles"
        ports:
          - containerPort: 80
          - containerPort: 443

      - name: db
        image: mariadb:10.3
        imagePullPolicy: IfNotPresent
        env:
         - name: "MYSQL_ROOT_PASSWORD"
           value: "rootpassword"
         - name: "TZ"
           value: "America/Los_Angeles"
        ports:
          - containerPort: 3306